name = "consulting-site"
compatibility_date = "2025-09-19"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
pages_build_output_dir = ".open-next/assets"
